# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('url', models.URLField(db_index=True)),
                ('type', models.CharField(blank=True, choices=[('DESKTOP', 'DESKTOP'), ('MOBILE', 'MOBILE'), ('TABLET', 'TABLET')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UrlVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='base.DeviceUrl')),
            ],
        ),
        migrations.AddField(
            model_name='deviceurl',
            name='main_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='base.Url'),
        ),
    ]
