# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceurl',
            name='url_id',
        ),
        migrations.AddField(
            model_name='url',
            name='url_id',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True),
        ),
    ]
